/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Unlock": "解锁",
    "Your": "你的",
    "Factors": "因子",
    "galaxy link": "星系链接",
    // "Hyper Game": "超级游戏",
    "hyper-points": "超级点数",
    "Locked!": "未解锁！",
    "On": "开启",
    "Number": "数字",
    "Requires": "需要",
    "Recent cascades:": "最近的级联：",
    "Currently x": "当前 x",
    "Reach certain amounts of shadow crystals to achieve shadow milestones!": "达到一定数量的 暗影水晶 即可实现暗影里程碑！",
    "Ordinal Pringles": "序数品客（Ordinal Pringles）",
    "other projects": "其它项目",
    "Manual save": "手动保存",
    "Cluster limit:": "集群限制：",
    "Cluster upgrade respec confirmation:": "集群升级 重洗 确认：",
    "Cluster upgrades are always bought at no cost": "集群升级始终免费购买",
    "Cluster your number [+": "对您的数字进行集群 [+",
    "Clusters": "集群",
    "Clusters (": "集群 (",
    "The end": "终点",
    "times/second": "次/秒",
    "total)": "总计)",
    "To be unlocked...": "待解锁...",
    "vectors per second": "向量每秒",
    "vectors": "向量",
    "Vectors": "向量",
    "Vectors no longer divide factor production (except in challenge 5)": "向量不再除以因子生产（挑战 5 除外）",
    "Shadow milestones": "暗影里程碑",
    "shadow power": "暗影之力",
    "shadow power/s (based on current hyper-points)": "暗影之力每秒（基于你当前的超级点数）",
    "shadow power gives you": "暗影之力给你",
    "Surpass the limits of cascade and go beyond!": "超越级联的极限，超越！",
    "the Basedverse": "基础宇宙",
    "up-base": "上基数",
    "down-base": "下基数",
    "This will allow you to gain more than 1 cascade per reset.": "这将使您在每次重置时获得超过 1 个级联。",
    "Recent": "最近",
    "Reset your number to gain": "重置您的数字以获得",
    "Hard reset": "硬重置",
    "Increase your number (I)": "提高你的数字（I）",
    "Gain max multipliers (M)": "获得最大乘数（M）",
    "challenges": "挑战",
    "Challenges": "挑战",
    "Each factor produces the one before it. 1st factors produce autoclickers.": "每一个因子都会产生它之前的一个因子。 第一个因子产生自动点击器。",
    "Enable vector gain": "启用向量增益",
    "Hyper-E": "超级-E",
    "(based on current number, only if vector gain is enabled)": "基于当前数量，仅当向量增益启用时）",
    "(The cluster limiter will not work if you already have more clusters than the limit)": "（如果您的集群数量已超过限制，集群限制器将不起作用）",
    "Also unlocks flavours": "还解锁了 flavours",
    "and": "和",
    "an autobuyer for factors (at no cost)": "一个因子自动购买器（免费）",
    "Auto-base shift:": "自动基数偏移：",
    "autoclickers are clicking the increase button": "自动点击器正在点击提高按钮",
    "Automatically buy post-cascade upgrade 1 at no cost": "自动免费购买级联后升级1",
    "Automatically gain clusters without resetting": "自动获取集群，无需重置（",
    "auto-base shift": "自动基数偏移",
    "base points": "基础点数",
    "base points (": "基础点数 (",
    "Base points": "基础点数",
    "Base points respec confirmation:": "基础点数 重洗 确认：",
    "blood crystals": "血液水晶",
    "Blood crystals multiply shadow power/s": "血液水晶乘以暗影力量/秒",
    "blood crystals, multiplying shadow power/s by": "血液水晶，乘以暗影力量/秒",
    "blood power": "血液力量",
    "blood power/s (based on current shadow power)": "血液力量/秒（基于你当前的暗影力量）",
    "blood power gives you": "血液力量给你",
    "Buy max factors (F)": "购买最大因子 (F)",
    "Buy max layers (F)": "购买最大层 (F)",
    "Cascade": "级联",
    "Cascade confirmation:": "级联确认：",
    "Cascade power effect is improved": "级联力量效果被提升了",
    "Cascade power, multiplying factor production by": "级联力量，乘以因子生产",
    "Cascade with certain amounts of clusters or less to achieve cascade milestones!": "级联一定数量或更少的集群，以实现级联里程碑！",
    "Exit current challenge": "退出当前挑战",
    "Factor autobuyer:": "因子自动购买器",
    "something...": "一些东西...",
    "Respec base points": "重洗基础点数",
    "Respec clusters": "重洗集群",
    "Reset previous progress to gain a cascade (C)": "重置之前的进度以获得级联 (C)",
    "Shadow crystals": "暗影水晶",
    "Shadow crystals multiply divine power/s": "暗影水晶乘以神圣力量/秒",
    "Want to stay up-to-date with updates and chat about the game? Check out the": "想要了解最新动态并讨论游戏吗？ 查看",
    "Want to support my game development efforts and get early access to updates? Check out my": "想要支持我的游戏开发工作并尽早获得更新吗？ 看看我的",
    "Double blood power/s": "双倍 血液力量/秒",
    "Double divine power/s": "双倍 神圣力量/秒",
    "Double shadow power/s": "双倍 暗影力量/秒",
    "Double vector gain [": "双倍 向量增益 [",
    "Each layer produces the one before it. Power producers produce power.": "每一层都会产生前一层。 力量生产器生产力量。",
    "clusters (": "集群（",
    "Completing challenges provides a x100 boost to the corresponding factor.": "完成挑战可将相应因子提高 100x。",
    "Congratulations, you've hit the end of Hyper Game! If you're still seeking more, you can check out my": "恭喜，您已完成 Hyper Game 的结尾！ 如果您还想了解更多，可以查看我的",
    "Cluster confirmation:": "集群确认：",
    "Challenge enter confirmation:": "挑战进入确认：",
    "Challenge exit confirmation:": "挑战退出确认：",
    "Challenge reward is ^1.5, and unlock layers": "挑战奖励^1.5，并解锁层",
    "Costs": "成本",
    "Keep vector upgrades on cascade reset": "在级联重置时保留向量升级",
    "Decrease basedverse base [": "减少 基础宇宙 基数 [",
    "Decrease blood crystal requirement": "减少 血液水晶 要求",
    "Decrease divine crystal requirement": "减少 神圣水晶 要求",
    "Decrease shadow crystal requirement": "减少 暗影水晶 要求",
    "divine power": "神圣力量",
    "divine power/s (based on current blood power)": "神圣力量/秒（根据当前血液力量）",
    "divine power gives you": "神圣力量给你",
    "divine crystals": "神圣水晶",
    "divine crystals, multiplying blood power/s by": "神圣水晶，乘以血液力量/秒 ",
    "Perform a base shift (S)": "执行基础偏移 (S)",
    "Hold shift for more upgrade info": "",
    "Hold shift to see bought factor amounts": "",
    "Hold shift to see bought layer amounts": "",
    "Hold shift to see current challenge boosts": "",
    "Buy max layers (L)": "购买最大层 (L)",
    "cascades!": "级联！",
    "cascade power, multiplying factor production by": "级联力量，乘以因子生产",
    "cascades": "级联",
    "Bought layers (+ power producers) multiply that layer's production": "购买的层（+力量产生器）使该层的产量成倍增加",
    "Basedverse enter/exit confirmation:": "基础宇宙进入/退出确认：",
    "Always gain 100 hyper-points per second": "始终每秒获得 100 个超级点数",
    "and cascade gain by": "和级联增益",
    "Max vector upgrades (V)": "最大向量升级 (V)",
    "Multiply autoclicker speed in challenges [": "在挑战中乘以自动点击器的速度 [",
    "Multiply cascade gain based on unspent clusters": "基于未使用的集群乘以级联增益",
    "Multiply factor production [": "乘以因子生产 [",
    "Multiply up-base and down-base effect [": "乘以上基数和下基数效果 [",
    "Multiplying factor production by x": "乘以因子生产 x",
    "Multiplying vector gain by x": "乘以向量增益 x",
    "You are gaining": "你获得了",
    "You are trapped in base": "你被困在基数里",
    "Your vectors are dividing factor production by": "您的向量将因子产量除以",
    "Vector upgrade 3 formula is improved": "向量升级3公式改进了",
    "Put all base points into up-base": "将所有基础点数放入上基数",
    "Put all base points into down-base": "将所有基础点数放入下基数",
    "Upon leaving you will gain base points based on your number.": "离开后，您将根据您的数字获得基础点数。",
    "Limit clusters:": "限制集群：",
    "Start every base shift with 1 3rd factor": "以 1 个第3因子开始每个基数偏移",
    "Keep base points on cascade reset": "级联重置时保留基础点数",
    "Total base points increase vector gain": "总基础点数增加向量增益",
    "Total challenges completed boosts autoclicker speed": "完成的挑战总数提高了自动点击器的速度",
    "Unspent clusters multiply factor production": "未使用的集群乘以因子生产",
    "Vectors increase vector gain": "向量提高向量增益",
    "Base is always 8 in challenges": "挑战中的基数始终为 8",
    "Automatically buy multipliers at no cost": "自动免费购买乘数",
    "Base shifts increase factor production": "基础偏移提高因子生产",
    "Gain 10% of best cascades per second (Currently": "每秒获得 10% 的最佳级联（当前",
    "Gain 100 hyper-points per second": "每秒获得 100 个超级点数",
    "Gain 100% of potential cascades per second": "每秒获得 100% 的潜在级联",
    "Gain 100% of potential hyper-points per second": "每秒获得 100% 的潜在超级点数",
    "Increase up/down-base effect based on time spent in this cascade": "根据在此级联中花费的时间增加上/下基数效果",
    "Increase vector gain based on total clusters [": "根据总集群数增加向量增益[",
    "Vector upgrade 3 formula is improved again": "向量升级3公式再次改进",
    "Multiply manual number incrementing by 10": "将手动数字增长乘以 10",
    "Multiplier effect is squared": "乘数效果是平方的",
    "and multiplying cascade gain by": "并将级联增益乘以",
    "Bought factors multiply that factor's production": "购买的因子使该因子的产量成倍增加",
    "Heavily inspired by": "深受启发来自",
    "HyperNum made with help from solarzone": "HyperNum 在 Solarzone 的帮助下制作",
    "Improve post-cascade upgrade 1 cost": "提高级联后升级1成本",
    "Keep challenge completions on cascade reset": "在级联重置时保留挑战完成",
    "Increase cascade gain [": "增加级联增益[",
    "Layer production is multiplied by (layers bought)^3 instead of ^1": "层产量乘以（购买的层数）^3，而不是 ^1",
    "Base is always 20 and you cannot base shift": "基数始终为 20 并且不能进行基数偏移",
    "Each base shift divides factor production by 10": "每个基础偏移将因子生产除以 10",
    "Each bought cluster upgrade divides autoclicker speed by 10,000": "每次购买的集群升级都会将自动点击器速度除以 10,000",
    "Factors beyond the 1st cannot be bought": "无法购买超出第 1 个因子的因子",
    "Put 1 base point into up-base": "将 1 个基础点数放入上基数",
    "Put 1 base point into down-base": "将 1 个基础点数放入下基数",
    "Vector gain is always enabled (capped at 10k/s), but resets on base shifts": "向量增益始终启用（上限为 10k/秒），但会在基数偏移时重置",
    "You cannot buy cluster upgrades, multipliers or 5th/6th factors": "您无法购买集群升级、乘数或第 5/第 6 因子",
    "Infinity": "无穷",
    "alpha-flavour": "alpha-flavour",
    "Alpha-flavour": "alpha-flavour",
    "Alpha-flavour effect is increased, and unlock": "alpha-flavour 效果增加，并解锁",
    "alpha-flavour!": "alpha-flavour!",
    "Also unlocks": "还解锁",
    "Always keep challenge completions, and unlock combinators": "始终保持挑战完成并解锁组合器",
    "Always keep shadow milestone 3, and keep cascade milestones": "始终保留影子里程碑 3，并保留级联里程碑",
    "an autobuyer for layers (at no cost)": "层的自动购买者（免费）",
    "Beta-flavour": "贝塔味",
    "beta-flavour!": "贝塔风味！",
    "Bought combinators (+ deuterium producers) multiply that combinator's production": "购买的组合器（+氘生产商）使组合器的产量成倍增加",
    "Buy max combinators": "购买最大组合器",
    "Completed challenges multiply shadow/blood/divine power gain": "完成的挑战使暗影/鲜血/神力增益倍增",
    "Delta-flavour": "三角洲风味",
    "delta-flavour!": "三角洲风味！",
    "deuteric": "氘代",
    "Deuteric": "氘代",
    "Deuteric challenge enter confirmation:": "Deuteric 挑战进入确认：",
    "Deuteric challenge exit confirmation:": "Deuteric 挑战退出确认：",
    "Deuteric challenges": "氘代挑战",
    "Deuteric challenges are completed upon performing a deuteric reset.": "执行氘核重置后，氘核挑战完成。",
    "Deuteric confirmation:": "氘代确认：",
    "Deuteric milestones are based on total deuteric, not current deuteric!": "氘核里程碑基于总氘核，而不是当前氘核！",
    "Deuterium producer [0]": "氘生产商 [0]",
    "Discord": "不和谐",
    "Each combinator produces the one before it. Deuterium producers produce deuterium.": "每个组合器都会产生前一个组合器。 氘生产商生产氘。",
    "Enter": "进入",
    "Epsilon-flavour": "厄普西隆风味",
    "flavours": "风味",
    "Flavours": "风味",
    "Flavours 2-5 are always equal to alpha-flavour amount": "风味 2-5 始终等于 alpha-flavour 数量",
    "Flavours are always equal to highest cascade amount": "风味始终等于最高级联量",
    "Gamma-flavour": "伽玛味",
    "gamma-flavour!": "伽玛味！",
    "Hold shift to see bought combinator amounts": "按住 Shift 键即可查看购买的组合器数量",
    "Hyper Game": "超级游戏",
    "Increase base point limit to 2500": "将基点上限提高至 2500",
    "Increase blood power gain and effect cap": "增加血力增益和效果上限",
    "Increase divine power gain and effect cap": "增加神力增益和效果上限",
    "Increase shadow power gain and effect cap": "增加暗影力量增益和效果上限",
    "Keep auto post-cascade upgrade 1 and autobuy crystal upgrades at no cost": "保持自动级联后升级1和免费自动购买水晶升级",
    "Keep factor autobuyer and 100% of hyper-points per second": "保持因子自动购买者和每秒 100% 的超积分",
    "Keep post-cascade upgrades (besides the 1st) on deuteric reset": "在氘核重置时保持级联后升级（除了第一个）",
    "Layer autobuyer:": "图层自动购买者：",
    "Layer production is squared": "层产量是平方",
    "Made by Demonin": "由恶魔制造",
    "Multiply combinator production by 10 and square deuterium effect": "将组合器产量乘以 10 和平方氘效应",
    "Not in this update!": "本次更新中没有！",
    "Note: Deuteric gain is limited to 1 on the first reset!": "注意：首次重置时 Deuteric 增益限制为 1！",
    "Patreon": "帕特隆",
    "post-cascade": "级联后",
    "Post-cascade": "级联后",
    "Recent deuterics:": "最近的氘代：",
    "Reset previous progress to gain a deuteric (D)": "重置先前的进度以获得氘气（D）",
    "Reward: Base point cap is increased": "奖励：基点上限增加",
    "Reward: Blood crystal effect cap is increased": "奖励：血晶效果上限提升",
    "Reward: Divine crystal effect cap is increased": "奖励：神晶效果上限提升",
    "Reward: Shadow crystal effect cap is increased": "奖励：暗影水晶效果上限增加",
    "slogs": "艰难",
    "Time played:": "游玩时间：",
    "Time this cascade: 0s, 0 cascades to get (0.00/s)": "级联时间：0s，0级联得到（0.00/s）",
    "Time this deuteric: 0s, 0 deuteric to get (0.00/s)": "计时这个氘气：0s，0个氘气得到（0.00/s）",
    "Up-base and down-base are always equal to total base points": "上基点和下基点始终等于总基点",
    "Vector gain is always enabled (with no downside) and vector uprades are auto-maxed": "矢量增益始终启用（没有缺点）并且矢量升级自动最大化",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "1st factor ": "第 1 因子 ",
    "2nd factor ": "第 2 因子 ",
    "3rd factor ": "第 3 因子 ",
    "1st layer ": "第 1 层 ",
    "2nd layer ": "第 2 层 ",
    "3rd layer ": "第 3 层 ",
    "Unlock ": "解锁 ",
    "Reset vectors to ": "将向量重置为 ",
    "Gain an autoclicker multiplier ": "获得一个自动点击器乘数 ",
    "Current effect: x": "当前效果: x",
    "Power producer [": "力量产生器 [",
    "Goal: ": "目标: ",
    "Achieve ": "达到 ",
    "Next at ": "下一个在 ",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    " cascade gain multiplier is increased": " 级联增益乘数增加了",
    " multiplies shadow power/s": "乘以暗影力量/秒",
    ", increasing factor production by ^": ", 提高因子生产 ^",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^你(.+)$/,
    /^挑战(.+)$/,
    /^成本(.+)$/,
    /^(.+)集群$/,
    /^\[([\d\.]+)e([\d\.,]+)\]$/,
    /^\[([\d\.,]+)\]$/,
    /^\[([\d\.]+)\]$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^([\d\.,]+)E([\d\.,]+)$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Each (.+) costs$/, '每个 $1 成本'],
    [/^Turn all (.+) into$/, '切换所有 $1 为'],
    [/^Requires (.+) in base (.+)$/, '需要 $1 到基数 $2'],
    [/^(.+), multiplying (.+) gain by$/, '$1，乘以 $2 增益 '],
    [/^You are gaining (.+) blood crystal every$/, '你获得 $1 血液水晶 每'],
    [/^You are gaining (.+) divine crystal every$/, '你获得 $1 神圣水晶 每'],
    [/^You are gaining (.+) shadow crystal every$/, '你获得 $1 暗影水晶 每'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.]+)e([\d\.,]+) hyper\-points$/, '$1e$2 超级点数'],
    [/^Beat challenge ([\d\.,]+) once$/, '完成挑战 $1 一次'],
    [/^Beat challenge ([\d\.,]+) ([\d\.,]+) times$/, '完成挑战 $1 $2 次'],
    [/^Challenge ([\d\.,]+) \($/, '挑战 $1（'],
    [/^([\d\.,]+)th factor (.+)$/, '第 $1 因子 $2'],
    [/^([\d\.,]+)th layer (.+)$/, '第 $1 层 $2'],
    [/^([\d\.,]+) in base ([\d\.,]+)$/, '$1 到基数 $2'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) deuteric$/, '$1 氘代'],
    [/^Costs ([\d\.,]+) deuteric$/, '成本 $1 氘代'],
    [/^([\d\.,]+) cr.$/, '$1 水晶'],
    [/^([\d\.,]+)e([\d\.,]+) cr.$/, '$1e$2 水晶'],
    [/^([\d\.,]+)st combinator \[([\d\.,]+)\]$/, '第$1 组合器 \[$2\]'],
    [/^([\d\.,]+)nd combinator \[([\d\.,]+)\]$/, '第$1 组合器 \[$2\]'],
    [/^([\d\.,]+)rd combinator \[([\d\.,]+)\]$/, '第$1 组合器 \[$2\]'],
    [/^([\d\.,]+)th combinator \[([\d\.,]+)\]$/, '第$1 组合器 \[$2\]'],
    [/^([\d\.,]+) crystals$/, '$1 水晶'],
    [/^([\d\.,]+) crystal$/, '$1 水晶'],
    [/^([\d\.,]+) cluster$/, '$1 集群'],
    [/^([\d\.,]+) clusters$/, '$1 集群'],
    [/^([\d\.,]+) hyper\-points$/, '$1 超级点数'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Costs (.+) blood power$/, '成本 $1 血液力量'],
    [/^Costs (.+) shadow power$/, '成本 $1 暗影力量'],
    [/^Costs (.+) hyper\-points$/, '成本 $1 超级点数'],
    [/^Costs (.+) cascades$/, '成本 $1 级联'],
    [/^Requires (.+) clusters$/, '需要 $1 集群'],
    [/^Requires (.+)E(.+)$/, '需要 $1E$2'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);